// Embed the built visual-editor IIFE into a TS module so the dashboard Worker can
// serve it from GET /editor (the bookmarklet loads it cross-origin onto the
// user's live page — ARCH §9.7). A Worker has no filesystem at runtime, so the
// editor's bytes must be inlined at build time. Mirrors packages/api's
// embed-snippet.mjs convention exactly.
//
// Output: src/lib/editor-asset.ts (git-ignored — a derivative of the editor's
// git-ignored dist/). Regenerated by the pre{dev,build,test,typecheck} hooks so
// it never drifts from the editor build.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const editorDist = resolve(here, "../../editor/dist/editor.js");
const repoRoot = resolve(here, "../../..");
const out = resolve(here, "../src/lib/editor-asset.ts");

if (!existsSync(editorDist)) {
  // dist/ is git-ignored; build the editor on demand (fresh checkout / CI).
  console.log("editor dist missing — building @kumikitools/editor…");
  execSync("npm run build --workspace @kumikitools/editor", {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

const js = readFileSync(editorDist, "utf8");
const banner =
  "// GENERATED by scripts/embed-editor.mjs — do not edit.\n" +
  "// Source: @kumikitools/editor dist (editor.js). Regenerated by pre-hooks.\n";

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${banner}export const EDITOR_JS = ${JSON.stringify(js)};\n`);
console.log(`embedded editor → src/lib/editor-asset.ts (${js.length} B)`);
