// Embed the built client snippet into a TS module so the Worker can serve it
// from /s.js with config baked in (ARCH §3a). A Worker has no filesystem at
// runtime, so the snippet's bytes must be inlined at build time.
//
// Output: src/snippet-asset.ts (git-ignored — a derivative of the snippet's
// git-ignored dist/). Regenerated by the pre{test,build,typecheck,dev} hooks so
// it never drifts from the snippet build.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const snippetDist = resolve(here, "../../snippet/dist/kumiki.min.js");
const repoRoot = resolve(here, "../../..");
const out = resolve(here, "../src/snippet-asset.ts");

if (!existsSync(snippetDist)) {
  // dist/ is git-ignored; build the snippet on demand (fresh checkout / CI).
  console.log("snippet dist missing — building @kumikitools/snippet…");
  execSync("npm run build --workspace @kumikitools/snippet", {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

const js = readFileSync(snippetDist, "utf8");
const banner =
  "// GENERATED by scripts/embed-snippet.mjs — do not edit.\n" +
  "// Source: @kumikitools/snippet dist (kumiki.min.js). Regenerated by pre-hooks.\n";

// JSON.stringify yields a valid, fully-escaped JS string literal. The asset is
// served as application/javascript (never inline HTML), so </script> / U+2028
// are non-issues.
writeFileSync(out, `${banner}export const SNIPPET_JS = ${JSON.stringify(js)};\n`);
console.log(`embedded snippet → src/snippet-asset.ts (${js.length} B)`);
